// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly title: "Coder";
  readonly summary: "Implement the plan as if you are the execution owner for this assignment.";
};
export type FrontMatter = typeof frontmatter;
export type Args = Record<never, never>;
export declare const prompt: (input?: Args | ((frontmatter: FrontMatter) => Args)) => string;
