// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly title: "Planner";
  readonly summary: "Turn the latest user request into a crisp proposal set that the rest of the";
};
export type FrontMatter = typeof frontmatter;
export type Args = Record<never, never>;
export declare const prompt: (input?: Args | ((frontmatter: FrontMatter) => Args)) => string;
