// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly title: "Reviewer";
  readonly summary: "Review the proposed work with a code review mindset.";
};
export type FrontMatter = typeof frontmatter;
export type Args = Record<never, never>;
export declare const prompt: (input?: Args | ((frontmatter: FrontMatter) => Args)) => string;
