// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly title: "Render JSON";
};
export type FrontMatter = typeof frontmatter;
export type Args = {
  readonly payload: unknown;
};
export declare const prompt: (input: Args | ((frontmatter: FrontMatter) => Args)) => string;
