// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: Record<never, never>;
export type FrontMatter = typeof frontmatter;
export type Args = {
  readonly name: unknown;
};
export declare const prompt: (input: Args | ((frontmatter: FrontMatter) => Args)) => string;
