import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import type {
  MeowFlowTeamConfigInput,
  NormalizedMeowFlowTeamConfig,
} from "@myriaddreamin/meow-flow-core";
import { loadMeowFlowTeamConfig } from "./team-config.js";
import {
  assertSupportedTeamConfigSourcePath,
  getSharedMeowFlowConfigPath,
} from "./shared-config.js";

export type SharedConfigInstallResult = {
  readonly sourceConfigPath: string;
  readonly tsconfigPath: string | null;
  readonly installedConfigPath: string;
  readonly didOverwrite: boolean;
  readonly config: NormalizedMeowFlowTeamConfig;
};

export function installSharedMeowFlowTeamConfig(input: {
  cwd: string;
  sourceConfigPath: string;
}): SharedConfigInstallResult {
  const cwd = path.resolve(input.cwd);
  const sourceConfigPath = path.resolve(cwd, input.sourceConfigPath);

  assertSupportedTeamConfigSourcePath(sourceConfigPath);

  const loadedConfig = loadMeowFlowTeamConfig({
    cwd,
    configPath: sourceConfigPath,
  });
  const installedConfigPath = getSharedMeowFlowConfigPath();
  const installedConfigDirectory = path.dirname(installedConfigPath);
  const didOverwrite = existsSync(installedConfigPath);

  mkdirSync(installedConfigDirectory, { recursive: true });
  writeFileSync(
    path.join(installedConfigDirectory, "package.json"),
    '{\n  "type": "commonjs"\n}\n',
  );
  writeFileSync(installedConfigPath, serializePortableTeamConfig(loadedConfig.config), "utf8");

  return {
    sourceConfigPath: loadedConfig.configPath,
    tsconfigPath: loadedConfig.tsconfigPath,
    installedConfigPath,
    didOverwrite,
    config: loadedConfig.config,
  };
}

function serializePortableTeamConfig(config: NormalizedMeowFlowTeamConfig): string {
  return [
    "// Generated by meow-flow config install. Re-run install instead of editing this file.",
    `module.exports = ${JSON.stringify(toPortableTeamConfig(config), null, 2)};`,
    "",
  ].join("\n");
}

function toPortableTeamConfig(config: NormalizedMeowFlowTeamConfig): MeowFlowTeamConfigInput {
  return {
    notifications: {
      target: config.notifications.target,
    },
    ...(config.dispatch.maxConcurrentWorkers === null
      ? {}
      : {
          dispatch: {
            maxConcurrentWorkers: config.dispatch.maxConcurrentWorkers,
          },
        }),
    repositories: config.repositories.map((repository) => ({
      id: repository.id,
      label: repository.label,
      directory: repository.directory,
      worktreeParentDirectory: repository.worktreeParentDirectory,
      worktreeTheme: repository.worktreeTheme,
    })),
  };
}
