// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly kind: "initial-prompt";
};
export type FrontMatter = typeof frontmatter;
export type Args = {
  readonly requestTopic: unknown;
};
export declare const prompt: (input: Args | ((frontmatter: FrontMatter) => Args)) => string;
