import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDirectory, "..");
const repositoryRoot = path.resolve(packageRoot, "..", "..");
const sourceDirectory = path.join(repositoryRoot, "skills");
const outputPath = path.join(packageRoot, "src", "embedded-skills.ts");

async function collectFiles(directory, relativePrefix = "") {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const absolutePath = path.join(directory, entry.name);
    const relativePath = path.posix.join(relativePrefix, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await collectFiles(absolutePath, relativePath)));
      continue;
    }

    if (!entry.isFile()) {
      continue;
    }

    if (!relativePath.endsWith(".md")) {
      continue;
    }

    files.push({
      path: relativePath,
      content: await fs.readFile(absolutePath, "utf8"),
    });
  }

  return files;
}

async function main() {
  const entries = await fs.readdir(sourceDirectory, { withFileTypes: true });
  const skills = [];

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) {
      continue;
    }

    const skillDirectory = path.join(sourceDirectory, entry.name);
    const files = await collectFiles(skillDirectory);

    if (!files.some((file) => file.path === "SKILL.md")) {
      throw new Error(`Missing SKILL.md in ${skillDirectory}`);
    }

    skills.push({
      name: entry.name,
      files,
    });
  }

  const content = [
    "// Generated by scripts/embed-skills.mjs. Do not edit by hand.",
    "",
    "export type EmbeddedSkillFile = {",
    "  readonly path: string;",
    "  readonly content: string;",
    "};",
    "",
    "export type EmbeddedSkill = {",
    "  readonly name: string;",
    "  readonly files: readonly EmbeddedSkillFile[];",
    "};",
    "",
    ...formatEmbeddedSkills(skills),
    "",
  ].join("\n");

  await fs.writeFile(outputPath, content, "utf8");
}

function formatEmbeddedSkills(skills) {
  const lines = ["export const EMBEDDED_SKILLS: readonly EmbeddedSkill[] = ["];

  for (const skill of skills) {
    lines.push("  {", `    name: ${JSON.stringify(skill.name)},`, "    files: [");

    for (const file of skill.files) {
      lines.push(
        "      {",
        `        path: ${JSON.stringify(file.path)},`,
        "        content:",
        `          ${toBestQuotedLiteral(file.content)},`,
        "      },",
      );
    }

    lines.push("    ],", "  },");
  }

  lines.push("];");
  return lines;
}

function toBestQuotedLiteral(value) {
  const singleQuoteCount = countOccurrences(value, "'");
  const doubleQuoteCount = countOccurrences(value, '"');

  return doubleQuoteCount <= singleQuoteCount
    ? `"${escapeLiteralContent(value, '"')}"`
    : `'${escapeLiteralContent(value, "'")}'`;
}

function countOccurrences(value, needle) {
  return value.split(needle).length - 1;
}

function escapeLiteralContent(value, quote) {
  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("\r", "\\r")
    .replaceAll("\n", "\\n")
    .replaceAll(quote, `\\${quote}`)
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
}

await main();
