// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly title: "OpenSpec Materializer";
  readonly summary: "Materialize OpenSpec proposal artifacts inside an existing change directory.";
};
export type FrontMatter = typeof frontmatter;
export type Args = {
  readonly repositoryPath: unknown;
  readonly worktreePath: unknown;
  readonly canonicalBranchName: unknown;
  readonly proposalBranchName: unknown;
  readonly proposalChangeName: unknown;
  readonly proposalPath: unknown;
  readonly expectedArtifacts: unknown;
  readonly worktreeRoot: unknown;
  readonly requestTitle: unknown;
  readonly conventionalTitle: unknown;
  readonly taskTitle: unknown;
  readonly taskObjective: unknown;
  readonly plannerSummarySection: unknown;
  readonly plannerDeliverableSection: unknown;
  readonly requestInputSection: unknown;
  readonly codexSkillContext: unknown;
};
export declare const prompt: (input: Args | ((frontmatter: FrontMatter) => Args)) => string;
