// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly title: "Planner";
  readonly summary: "Turn the latest user request into a crisp proposal set that the rest of the team can execute after human approval.";
};
export type FrontMatter = typeof frontmatter;
export type Args = {
  readonly teamName: unknown;
  readonly ownerName: unknown;
  readonly objective: unknown;
  readonly repositoryContext: unknown;
  readonly workflow: unknown;
  readonly assignmentNumber: unknown;
  readonly workerCount: unknown;
  readonly localSkillReference: unknown;
  readonly openSpecSkills: unknown;
  readonly openSpecSkillReference: unknown;
  readonly requestContext: unknown;
  readonly handoffs: unknown;
  readonly maxProposalCount: unknown;
};
export declare const prompt: (input: Args | ((frontmatter: FrontMatter) => Args)) => string;
