// Generated by meow-prompt. Do not edit by hand.
export declare const frontmatter: {
  readonly title: "Reviewer";
  readonly summary: "Review the proposed work with a code review mindset.";
};
export type FrontMatter = typeof frontmatter;
export type Args = {
  readonly roleName: unknown;
  readonly teamName: unknown;
  readonly ownerName: unknown;
  readonly objective: unknown;
  readonly repositoryName: unknown;
  readonly repositoryPath: unknown;
  readonly branchName: unknown;
  readonly baseBranch: unknown;
  readonly worktreePath: unknown;
  readonly implementationCommitSection: unknown;
  readonly laneIndex: unknown;
  readonly taskTitle: unknown;
  readonly taskObjective: unknown;
  readonly requestTitle: unknown;
  readonly conventionalTitle: unknown;
  readonly planSummary: unknown;
  readonly planDeliverable: unknown;
  readonly plannerNoteSection: unknown;
  readonly workflow: unknown;
  readonly handoffs: unknown;
  readonly assignmentInput: unknown;
  readonly codexSkillContext: unknown;
  readonly reviewerExecutionRules: unknown;
};
export declare const prompt: (input: Args | ((frontmatter: FrontMatter) => Args)) => string;
